name = "traecn-ai-info-generator"
main = "dist/index.js"
compatibility_date = "2023-12-18"

[[d1_databases]]
binding = "DB"
database_name = "ai-info-generator-db-2847"
database_id = "c55fe53f-5171-4955-a207-1ba623b5c8df"

[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "passwd1234"

[build]
command = "npm run build"

[assets]
directory = "client/dist"
binding = "ASSETS"